Feat/normal authentication
TEAM-PIN-UP/BE-PIN-UP pull request #23
Opened 2024-11-05 07:48 UTC by kwonyonghyun

## #️⃣연관된 이슈
> ex) * #21 

## 📝작업한 내용
> OAuth가 아닌 일반 회원가입/로그인 기능 구현

## PR 종류
- [x] 기능 추가

2024-11-06 12:48 UTC, BellWin98 requested changes
고생하셨습니다:)

2024-11-06 12:48 UTC, BellWin98 commented on docker-compose.yml
> +      SPRING_DATASOURCE_PASSWORD: QGWGPnEGBW8Ss1Dm3I7o
용현님 로컬 DB 패스워드 인가요?

2024-11-06 12:48 UTC, BellWin98 commented on docker-compose.yml
> +      SPRING_DATASOURCE_URL: jdbc:mariadb://pinup_db:3306/pinup?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
application.yml ddl-auto를 create로 하면 DB가 생성될텐데, createDatabaseIfNotExist=true 를 넣으신 이유가 있을까요??

2024-11-07 01:25 UTC, kwonyonghyun commented on docker-compose.yml
> +      SPRING_DATASOURCE_URL: jdbc:mariadb://pinup_db:3306/pinup?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
docker compose up을 한 경우에, 테이블을 생성하는 쿼리가 생성되지 않아서 데이터베이스에 테이블이 존재하지 않는 에러를 발견해서 추가하게 되었습니다!. 

코드 수정할때 참고한 블로그 첨부합니다 :)
https://velog.io/@lynnchoi0126/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8-%EC%8B%A4%ED%96%89-%EC%8B%9C-JPA-%ED%85%8C%EC%9D%B4%EB%B8%94-%EC%83%9D%EC%84%B1%EC%9D%B4-%EC%95%88-%EB%90%98%EB%8A%94-%EC%98%A4%EB%A5%98

2024-11-07 01:36 UTC, kwonyonghyun commented on docker-compose.yml
> +      SPRING_DATASOURCE_PASSWORD: QGWGPnEGBW8Ss1Dm3I7o
docker-compose.yml에 MARIADB_ROOT_PASSWORD: QGWGPnEGBW8Ss1Dm3I7o로 설정되어 있어서 SPRING_DATASOURCE_PASSWORD: 1234로 설정을 하는 경우에 데이터베이스에 접근하지 못하는 오류가 발생했습니다. 혹시 의도적으로 SPRING_DATASOURCE_PASSWORD: 1234로 설정하신 거라면, 이유를 알 수 있을까요??

2024-11-13 13:42 UTC, BellWin98 approved these changes
고생하셨습니다

2024-11-13 13:42 UTC, merged