Feature/editor article
TEAM-PIN-UP/BE-PIN-UP pull request #24
Opened 2024-11-16 04:17 UTC by kwonyonghyun

## #️⃣연관된 이슈
#22 

## 📝작업한 내용
> editor article 기능 구현 완료했습니다 :)

## PR 종류
> 어떤 종류의 PR인지 아래 항목 중에 체크

- [x] 기능 추가

2024-11-26 10:41 UTC, BellWin98 requested changes
고생하셨습니다~

2024-11-26 10:41 UTC, BellWin98 commented on src/main/java/com/pinup/entity/Member.java
> +    @OneToMany(mappedBy = "author", fetch = FetchType.LAZY)
@OneToMany 기본값이 Lazy라 지워도 상관없을 것 같습니다!

2024-11-26 10:41 UTC, BellWin98 commented on src/main/java/com/pinup/global/config/SecurityConfig.java
> +@EnableMethodSecurity
권한 때문에 어노테이션 적용하신 것 같은데 어느 용도로 사용하시는 건지 알 수 있을까요?

2024-11-26 10:41 UTC, BellWin98 commented on src/main/java/com/pinup/service/ArticleService.java
> +        Member currentMember = getCurrentMember();
유저 검증 코드를 가장 앞 단에 위치하는 것이 어떨까요? 이미지 업로드 이후 유저 검증 실패 예외가 터지면 이미지는 S3에 그대로 남게 될 것 같아요!

2024-11-27 14:45 UTC, kwonyonghyun commented on src/main/java/com/pinup/global/config/SecurityConfig.java
> +@EnableMethodSecurity
Article Controller의 create article 함수에 @PreAuthorize("hasRole('ROLE_ADMIN')")를 적용하기 위해 사용했습니다!

2024-11-27 23:37 UTC, BellWin98 approved these changes

2024-11-27 23:37 UTC, merged