[Feat] 회원 프로필 조회, 리뷰 조회 동작 방식 수정
TEAM-PIN-UP/BE-PIN-UP pull request #33
Opened 2024-12-28 09:05 UTC by kwonyonghyun

## 📝작업한 내용
> MemberProfileResponse 수정 및 그에 따른 서비스 계층 수정, review에서 포토리뷰와 텍스트 리뷰로 분리 및 포토 리뷰 미리보기 추가

## PR 종류
- [x] 기능 추가

2024-12-28 13:19 UTC, BellWin98 requested changes
고생하셨습니다~

2024-12-28 13:19 UTC, BellWin98 commented on src/main/java/com/pinup/controller/ReviewController.java
>  public class ReviewController {
1. 포토 리뷰 상세와 텍스트 리뷰 상세 API를 호출했을 때, 반환 데이터를 리스트로 받는 이유를 알 수 있을까요?
2. 나 자신과 친구 API를 따로 나누지 않고, 하나로 합친 후 PathVariable로 memberId를 받는 건 어떨까요? 내 피드든 친구 피드든 보여지는 데이터가 동일해서 따로 나눌 필요가 없을 것 같아서요!
3. 피그마 디자인을 참고했을 때, 포토 리뷰는 상세 조회 API가 필요하지만, 텍스트 리뷰의 경우에는 상세 조회 API가 없어도 될 것 같아요!

2024-12-28 13:19 UTC, BellWin98 commented on src/main/java/com/pinup/dto/response/ProfileResponse.java
>  public class ProfileResponse {
프로필 데이터에 해당 유저와의 친구요청 상태값이 필요할 것 같습니다. (친구인지, 친구요청 보낸 상태인지, 자기 자신인지)

2024-12-28 15:38 UTC, kwonyonghyun commented on src/main/java/com/pinup/controller/ReviewController.java
>  public class ReviewController {
2번 제외하고는 모두 반영했습니다! 나 자신과 친구 API를 따로 두지 않으면 회원 생성시, FriendShip Entity에 자기 자신을 친구라고 넣어줘야 되는데 이게 조금 어색하다고 느꼈고, 전체 member profile 조회에 관해서 여쭤봤을때 "본인"과 "친구" 프로필 조회 엔드포인트 같은 경우에는 명확성 때문에 분리하는것도 좋을 것 같다고 하셔서 우선은 분리해뒀습니다! 이것에 대해서는 피드백을 주시면 감사하겠습니다!

2024-12-28 15:39 UTC, kwonyonghyun commented on src/main/java/com/pinup/dto/response/ProfileResponse.java
>  public class ProfileResponse {
친구 요청 상태값 대신, MemberRelationType이라는 새로운 Enum class를 정의하여 사용했습니다!

2024-12-30 02:37 UTC, BellWin98 approved these changes

2024-12-30 02:37 UTC, merged