별명으로 회원 검색 구현 #3
TEAM-PIN-UP/BE-PIN-UP pull request #4
Opened 2024-09-13 11:50 UTC by kwonyonghyun

## #3 

## 
> 별명으로 멤버 검색하는 기능을 구현하였습니다. 

## PR 종류
> 어떤 종류의 PR인지 아래 항목 중에 체크
- [ ] 버그 수정
- [x] 기능 추가
- [ ] 코드 스타일 변경 (formatting, local variables)
- [ ] 리팩토링 (기능 변경 X)
- [ ] 빌드 관련 수정
- [ ] 문서 내용 수정
- [ ] 테스트 추가
- [ ] 그 외, 어떤 종류인지 기입 바람:

## 💬리뷰 요구사항

> 별명으로 찾은 멤버 목록을 List로 반환할지 Page로 반환할지 고민했는데, 닉네임으로 검색되는 회원수가 많지 않을 것 같아 우선 List로 구현하였습니다. Page로 구현하는 것이 더 좋은 방법일까요?

2024-09-14 14:24 UTC, BellWin98 requested changes
고생많으셨습니다~!

2024-09-14 14:24 UTC, BellWin98 commented on src/main/java/com/pinup/repository/MemberRepository.java
> +    List<Member> findByNicknameContainingIgnoreCase(String query);
ContainingIgnoreCase가 대소문자 구분 없이 검색하는 기능이었군요! 한 수 배워갑니다~

2024-09-14 14:24 UTC, BellWin98 commented on src/main/java/com/pinup/service/SearchService.java
> +        List<Member> users = memberRepository.findByNicknameContainingIgnoreCase(query);
List냐 Page냐는 기획에 따라 달라질 것 같습니다. 자동완성으로 할 수도 있고, 닉네임을 정확하게 입력한 후 검색 버튼을 클릭해서 1명의 친구만 반환할 수도 있어요. 이 부분은 기획팀과 좀 더 상의해보시죠!

2024-09-14 14:24 UTC, BellWin98 commented on src/main/java/com/pinup/service/SearchService.java
> +    private MemberSearchResponse convertToUserSearchResponse(Member member) {
이 메서드를 Service단에 두지 말고, ResponseDto에 정적 팩토리 메서드로 추가해서 사용해보는 건 어떨까요? 관련 참고 링크 걸어 드립니다! 장단점이 있으니 취사선택하시면 될 것 같아요~!

[정적 팩토리 메서드 적용](https://velog.io/@gnoesnooj/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-%EC%A0%81%EC%9A%A9)

2024-09-23 14:11 UTC, BellWin98 requested changes
SSE 알림 기능 어려운 기능인데 이렇게 빨리 구현하시다니 능력자시네요!! 감탄하고 갑니다 ㅎㅎ

고생하셨습니다!

2024-09-23 14:11 UTC, BellWin98 commented on src/main/java/com/pinup/repository/MemberRepository.java
> +    List<Member> findByNicknameContainingIgnoreCase(String query);
닉네임으로 조회했을 때 반환 형태를 List로 받는 이유가 있으실까요? 닉네임은 유니크해서 하나의 데이터만 반환될 것 같아서요!!

2024-09-23 14:11 UTC, BellWin98 commented on src/main/java/com/pinup/service/FriendRequestService.java
> +        notificationService.sendNotification(new NotificationRequest(receiverId.toString(),
알림 발송할 때마다 DTO객체를 생성하게 되면 불필요한 메모리 차지가 될 것 같은데, 혹시 따로 추가하신 이유가 궁금합니다! 

DTO 생성 필요 없이 위 코드의 receiver와 sender객체를 가져다 써도 좋을 것 같아요:)

2024-09-23 14:11 UTC, BellWin98 commented on src/main/java/com/pinup/dto/request/NotificationRequest.java
> +public class NotificationRequest {
이 DTO의 필요성에 대해 고민해볼 필요가 있을 것 같습니다!

2024-09-23 15:06 UTC, kwonyonghyun commented on src/main/java/com/pinup/repository/MemberRepository.java
> +    List<Member> findByNicknameContainingIgnoreCase(String query);
메서드명에 'Containing'이 포함되어 있어, 부분 일치 검색을 구현하고 있습니다. 그 이유로 List를 사용했습니다!
 완전 일치 검색을 구현하는 것이 더 나은 방법일까요?

2024-09-23 17:42 UTC, kwonyonghyun commented
<img width="795" alt="스크린샷 2024-09-24 오전 2 40 20" src="https://github.com/user-attachments/assets/40342410-0928-489e-8e25-bb84a39cc802">

친구 맺기 관련 기능 설계서를 다시 본 결과, 종승님 말씀대로 부분 일치가 아닌 완전 일치로 구현하는 것이 맞을 것 같아 수정하였습니다! 그 외 코멘트 주신부분 모두 수정 완료했습니다. 오늘도 종승님 덕분에 많이 배웠습니다!

2024-09-23 22:38 UTC, BellWin98 approved these changes

2024-09-23 22:38 UTC, merged